// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk_lbRdZmrZR1cYr6ahNGdyHFIiEHyEhQ',
    appId: '1:320975730909:web:7389ce43b0c2652a4dc334',
    messagingSenderId: '320975730909',
    projectId: 'capstone-project-e54cd',
    authDomain: 'capstone-project-e54cd.firebaseapp.com',
    storageBucket: 'capstone-project-e54cd.appspot.com',
    measurementId: 'G-L73CHLG0CZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqONvo3ekDUZcH-gCwPKhm1yUVd10D37M',
    appId: '1:320975730909:android:15e473e4b352020e4dc334',
    messagingSenderId: '320975730909',
    projectId: 'capstone-project-e54cd',
    storageBucket: 'capstone-project-e54cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdy-wzHN2hn8FwwfI0JorFmp2rUoO1Mik',
    appId: '1:320975730909:ios:16359af6aabd9e1c4dc334',
    messagingSenderId: '320975730909',
    projectId: 'capstone-project-e54cd',
    storageBucket: 'capstone-project-e54cd.appspot.com',
    iosClientId: '320975730909-dsjlsm2lfjn5boedas57avg1d7do5ilv.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdy-wzHN2hn8FwwfI0JorFmp2rUoO1Mik',
    appId: '1:320975730909:ios:16359af6aabd9e1c4dc334',
    messagingSenderId: '320975730909',
    projectId: 'capstone-project-e54cd',
    storageBucket: 'capstone-project-e54cd.appspot.com',
    iosClientId: '320975730909-dsjlsm2lfjn5boedas57avg1d7do5ilv.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstone',
  );
}
